// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFUh2y2lt3cYw5So6ZoFeUW2hZwASHVKM',
    appId: '1:506327859876:web:15c23eb60a27a9f1969c31',
    messagingSenderId: '506327859876',
    projectId: 'finance-d01fd',
    authDomain: 'finance-d01fd.firebaseapp.com',
    storageBucket: 'finance-d01fd.firebasestorage.app',
    measurementId: 'G-8JZ6T2YE3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1cWRy8hPeHgn-8mHu_MCFck1gAxzBKDA',
    appId: '1:506327859876:android:2e3de931f99048c4969c31',
    messagingSenderId: '506327859876',
    projectId: 'finance-d01fd',
    storageBucket: 'finance-d01fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Fap_EgNr-A7cJ8eJVDITfrPrZEvu2g8',
    appId: '1:506327859876:ios:b0c85d3eb4e10dfc969c31',
    messagingSenderId: '506327859876',
    projectId: 'finance-d01fd',
    storageBucket: 'finance-d01fd.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Fap_EgNr-A7cJ8eJVDITfrPrZEvu2g8',
    appId: '1:506327859876:ios:b0c85d3eb4e10dfc969c31',
    messagingSenderId: '506327859876',
    projectId: 'finance-d01fd',
    storageBucket: 'finance-d01fd.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFUh2y2lt3cYw5So6ZoFeUW2hZwASHVKM',
    appId: '1:506327859876:web:aba6b724cb55831a969c31',
    messagingSenderId: '506327859876',
    projectId: 'finance-d01fd',
    authDomain: 'finance-d01fd.firebaseapp.com',
    storageBucket: 'finance-d01fd.firebasestorage.app',
    measurementId: 'G-J5DFPPD6C6',
  );
}
